// Fact, History, Map, and Game Fact Service for Discover Tab
import { Fact, HistoricalEvent, MapFact, GameFact } from '../types';

// Mock Data
const facts: Fact[] = [
  {
    id: '1',
    text: 'Bananas are berries, but strawberries are not.',
    category: 'science',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg',
    source: 'https://en.wikipedia.org/wiki/Banana',
    relatedFactIds: ['2'],
  },
  {
    id: '2',
    text: 'Honey never spoils. Archaeologists have found edible honey in ancient Egyptian tombs.',
    category: 'history',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Honey_comb.png',
    source: 'https://en.wikipedia.org/wiki/Honey',
    relatedFactIds: ['1'],
  },
  {
    id: '3',
    text: 'Octopuses have three hearts and blue blood.',
    category: 'nature',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Octopus2.jpg',
    source: 'https://en.wikipedia.org/wiki/Octopus',
    relatedFactIds: ['4'],
  },
  {
    id: '4',
    text: 'A group of flamingos is called a "flamboyance".',
    category: 'nature',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Flamingos_Laguna_Colorada_Bolivia_Luca_Galuzzi_2006.jpg',
    source: 'https://en.wikipedia.org/wiki/Flamingo',
    relatedFactIds: ['3'],
  },
  {
    id: '5',
    text: 'Venus is the only planet that spins clockwise.',
    category: 'space',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Venus-real_color.jpg',
    source: 'https://en.wikipedia.org/wiki/Venus',
    relatedFactIds: [],
  },
  {
    id: '6',
    text: "The world's largest desert is not the Sahara, but Antarctica.",
    category: 'geography',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Antarctica_6400px_from_Blue_Marble.jpg',
    source: 'https://en.wikipedia.org/wiki/Antarctic_Desert',
    relatedFactIds: [],
  },
  {
    id: '7',
    text: 'Wombat poop is cube-shaped.',
    category: 'nature',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Vombatus_ursinus_-Maria_Island_National_Park.jpg',
    source: 'https://en.wikipedia.org/wiki/Wombat',
    relatedFactIds: [],
  },
  {
    id: '8',
    text: 'The Eiffel Tower was originally intended for Barcelona.',
    category: 'history',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg',
    source: 'https://en.wikipedia.org/wiki/Eiffel_Tower',
    relatedFactIds: [],
  },
  {
    id: '9',
    text: 'Sharks existed before trees.',
    category: 'science',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/White_shark.jpg',
    source: 'https://en.wikipedia.org/wiki/Shark',
    relatedFactIds: [],
  },
  {
    id: '10',
    text: 'A day on Mercury is longer than its year.',
    category: 'space',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg',
    source: 'https://en.wikipedia.org/wiki/Mercury_(planet)',
    relatedFactIds: [],
  },
];

const historicalEvents: HistoricalEvent[] = [
  {
    id: '1',
    date: '1969-07-20',
    title: 'First Moon Landing',
    description: 'Apollo 11 astronauts Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Apollo_11_bootprint.jpg',
    source: 'https://en.wikipedia.org/wiki/Apollo_11',
  },
  {
    id: '2',
    date: '1928-09-28',
    title: 'Discovery of Penicillin',
    description: 'Alexander Fleming discovered penicillin, the first true antibiotic.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Alexander_Fleming2.jpg',
    source: 'https://en.wikipedia.org/wiki/Penicillin',
  },
  {
    id: '3',
    date: '2008-08-08',
    title: 'Beijing Olympics Opening Ceremony',
    description: 'The 2008 Summer Olympics opened in Beijing, China, with a spectacular ceremony.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Beijing_national_stadium.jpg',
    source: 'https://en.wikipedia.org/wiki/2008_Summer_Olympics',
  },
  {
    id: '4',
    date: '1989-11-09',
    title: 'Fall of the Berlin Wall',
    description: 'The Berlin Wall, dividing East and West Berlin, was opened, leading to German reunification.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Berlinermauer.jpg',
    source: 'https://en.wikipedia.org/wiki/Berlin_Wall',
  },
  {
    id: '5',
    date: '2001-09-11',
    title: 'September 11 Attacks',
    description: 'Terrorist attacks destroyed the World Trade Center in New York City.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/World_Trade_Center_-_New_York_City.jpg',
    source: 'https://en.wikipedia.org/wiki/September_11_attacks',
  },
  {
    id: '6',
    date: '1953-05-29',
    title: 'First Ascent of Mount Everest',
    description: 'Sir Edmund Hillary and Tenzing Norgay became the first climbers confirmed to have reached the summit of Mount Everest.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Mount_Everest_as_seen_from_Drukair2_PLW_edit.jpg',
    source: 'https://en.wikipedia.org/wiki/1953_British_Mount_Everest_expedition',
  },
  {
    id: '7',
    date: '1776-07-04',
    title: 'U.S. Declaration of Independence',
    description: 'The United States declared independence from Great Britain.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Us_declaration_independence.jpg',
    source: 'https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence',
  },
  {
    id: '8',
    date: '1986-01-28',
    title: 'Challenger Disaster',
    description: 'The Space Shuttle Challenger broke apart 73 seconds into its flight, leading to the deaths of seven astronauts.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/STS-51-L_explosion.jpg',
    source: 'https://en.wikipedia.org/wiki/Space_Shuttle_Challenger_disaster',
  },
  {
    id: '9',
    date: '1990-10-03',
    title: 'German Reunification',
    description: 'East and West Germany were officially reunited into a single nation.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Brandenburger_Tor_Berlin_2002.jpg',
    source: 'https://en.wikipedia.org/wiki/German_reunification',
  },
  {
    id: '10',
    date: '2004-12-26',
    title: 'Indian Ocean Earthquake and Tsunami',
    description: 'A massive undersea earthquake triggered a tsunami that devastated coastal areas in Southeast Asia.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/2004_Indian_Ocean_earthquake_and_tsunami_-_Sumatra.jpg',
    source: 'https://en.wikipedia.org/wiki/2004_Indian_Ocean_earthquake_and_tsunami',
  },
];

const mapFacts: MapFact[] = [
  {
    id: '1',
    country: 'Japan',
    fact: 'Japan has more than 5 million vending machines, selling everything from drinks to umbrellas.',
    coordinates: { lat: 36.2048, lng: 138.2529 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Japanese_vending_machines.jpg',
    source: 'https://en.wikipedia.org/wiki/Vending_machine',
  },
  {
    id: '2',
    country: 'Egypt',
    fact: 'Ancient Egyptians used honey as a sweetener and in tombs for preservation.',
    coordinates: { lat: 26.8206, lng: 30.8025 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Egypt.Giza.Sphinx.02.jpg',
    source: 'https://en.wikipedia.org/wiki/Ancient_Egyptian_cuisine',
  },
  {
    id: '3',
    country: 'Australia',
    fact: 'Australia is home to more kangaroos than people.',
    coordinates: { lat: -25.2744, lng: 133.7751 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Kangaroo_Australia_01.jpg',
    source: 'https://en.wikipedia.org/wiki/Kangaroo',
  },
  {
    id: '4',
    country: 'Brazil',
    fact: "The Amazon rainforest produces more than 20% of the world's oxygen supply.",
    coordinates: { lat: -14.2350, lng: -51.9253 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Amazon_Rainforest.jpg',
    source: 'https://en.wikipedia.org/wiki/Amazon_rainforest',
  },
  {
    id: '5',
    country: 'Canada',
    fact: 'Canada has more lakes than the rest of the world combined.',
    coordinates: { lat: 56.1304, lng: -106.3468 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Lake_Louise_Alberta_Canada_Banff_NP.jpg',
    source: 'https://en.wikipedia.org/wiki/Lake',
  },
  {
    id: '6',
    country: 'Italy',
    fact: 'Venice is built on more than 100 small islands in a lagoon in the Adriatic Sea.',
    coordinates: { lat: 45.4408, lng: 12.3155 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Venice_and_its_lagoon.jpg',
    source: 'https://en.wikipedia.org/wiki/Venice',
  },
  {
    id: '7',
    country: 'India',
    fact: 'The Kumbh Mela gathering in India is visible from space.',
    coordinates: { lat: 20.5937, lng: 78.9629 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Kumbh_Mela_2013.jpg',
    source: 'https://en.wikipedia.org/wiki/Kumbh_Mela',
  },
  {
    id: '8',
    country: 'Russia',
    fact: 'Lake Baikal in Russia is the deepest and oldest freshwater lake in the world.',
    coordinates: { lat: 53.5587, lng: 108.1650 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Lake_Baikal_Satellite_Picture.jpg',
    source: 'https://en.wikipedia.org/wiki/Lake_Baikal',
  },
  {
    id: '9',
    country: 'USA',
    fact: 'The United States is the only country to have put a man on the moon.',
    coordinates: { lat: 37.0902, lng: -95.7129 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Apollo_11_Lunar_Module_on_the_Moon.jpg',
    source: 'https://en.wikipedia.org/wiki/Moon_landing',
  },
];

const gameFacts: GameFact[] = [
  {
    id: '1',
    text: 'The Eiffel Tower can be 15 cm taller during hot days.',
    isTrue: true,
    explanation: 'Metal expands with heat, so the Eiffel Tower can grow taller in summer.',
    source: 'https://en.wikipedia.org/wiki/Eiffel_Tower',
  },
  {
    id: '2',
    text: 'Goldfish only have a memory of three seconds.',
    isTrue: false,
    explanation: 'Goldfish have been shown to have memories that last for months.',
    source: 'https://en.wikipedia.org/wiki/Goldfish',
  },
  {
    id: '3',
    text: 'Humans and giraffes have the same number of neck vertebrae.',
    isTrue: true,
    explanation: 'Both have seven neck vertebrae, though giraffes have much longer ones.',
    source: 'https://en.wikipedia.org/wiki/Giraffe',
  },
  {
    id: '4',
    text: 'Venus is the hottest planet in our solar system.',
    isTrue: true,
    explanation: 'Venus has a thick atmosphere that traps heat, making it hotter than Mercury.',
    source: 'https://en.wikipedia.org/wiki/Venus',
  },
  {
    id: '5',
    text: 'The Great Wall of China is visible from the Moon.',
    isTrue: false,
    explanation: 'This is a myth; the Great Wall is not visible from the Moon with the naked eye.',
    source: 'https://en.wikipedia.org/wiki/Great_Wall_of_China',
  },
  {
    id: '6',
    text: 'A snail can sleep for three years.',
    isTrue: true,
    explanation: 'Some snails can hibernate for up to three years in unfavorable conditions.',
    source: 'https://en.wikipedia.org/wiki/Snail',
  },
  {
    id: '7',
    text: 'Lightning never strikes the same place twice.',
    isTrue: false,
    explanation: 'Lightning can and does strike the same place multiple times.',
    source: 'https://en.wikipedia.org/wiki/Lightning',
  },
  {
    id: '8',
    text: 'The human body has four lungs.',
    isTrue: false,
    explanation: 'Humans have two lungs.',
    source: 'https://en.wikipedia.org/wiki/Lung',
  },
  {
    id: '9',
    text: 'Bats are blind.',
    isTrue: false,
    explanation: 'Bats can see, but they also use echolocation to navigate.',
    source: 'https://en.wikipedia.org/wiki/Bat',
  },
  {
    id: '10',
    text: 'The unicorn is the national animal of Scotland.',
    isTrue: true,
    explanation: 'The unicorn is a symbol of purity and innocence in Celtic mythology and is Scotland\'s national animal.',
    source: 'https://en.wikipedia.org/wiki/Unicorn',
  },
];

export const factService = {
  getFactOfTheDay: (): Fact => facts[Math.floor(Math.random() * facts.length)],
  getAllFacts: (): Fact[] => facts,
  getFactById: (id: string): Fact | undefined => facts.find(f => f.id === id),
  getRelatedFacts: (id: string): Fact[] => {
    const fact = facts.find(f => f.id === id);
    return fact?.relatedFactIds?.map(rid => facts.find(f => f.id === rid)).filter(Boolean) as Fact[];
  },
  getHistoricalEventsByDate: (date: string): HistoricalEvent[] => historicalEvents.filter(e => e.date.endsWith(date.slice(5))),
  getAllHistoricalEvents: (): HistoricalEvent[] => historicalEvents,
  getMapFacts: (): MapFact[] => mapFacts,
  getMapFactByCountry: (country: string): MapFact | undefined => mapFacts.find(f => f.country === country),
  getGameFacts: (): GameFact[] => gameFacts,
  getRandomGameFact: (): GameFact => gameFacts[Math.floor(Math.random() * gameFacts.length)],
}; 